"""This library provides cool features for data processing and analysis."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/cool_lib.ipynb.

# %% auto 0
__all__ = ['foo', 'go_duckies_yourself']

# %% ../nbs/cool_lib.ipynb 3
def foo(): print("foo")

# %% ../nbs/cool_lib.ipynb 4
def go_duckies_yourself(to):
    """Tells someone to go duckies themselves."""
    return f"go duckies yourself {to}"
